### ISSUE TITLE
Should we move from organizational accounts to individual accounts?

### ISSUE THREAD

**Issue by seamustuohy** [ASL-19/civicdr#11]
User accounts (IP & SP) on the CiviCDR platform are “organizational accounts” instead of traditional “user accounts.”

Only a single implementing partner and service provider pair are allowed to be assigned to a single ticket within the CiviCDR platform. Tickets can be re-assigned to different users within the system. Multiple implementing partners cannot monitor a single ticket. This  removes the ability for multiple users who belong to a single organization to collectively monitoring a ticket. 
 
This was met with two main concerns by the participants.
* For these types of accounts to work, IPs will need to be provided guidance on how to properly use an organizational account within their existing workflows. 
  * This is not a common set-up for online applications and IPs will be unfamiliar with it.
  * Setting up multi-factor authentication on multiple devices is rarely done. [It is a more difficult process that is largely undocumented.]( http://joelclermont.com/2012/06/08/using-google-authenticator-on-more-than-one-device/) IPs will need assistance in doing this correctly.  
* There are additional security concerns that come with the use of shared accounts. 
  * The more users who have credentials for an account the more opportunities for that account to be compromised. 
  * The shared nature of the accounts means that an organizations tickets will not be able to be split across accounts. Therefore there will be a larger set of ticket information in each IP organizations accounts than a single user account would have. 
 
With proper guidance and hands-on support by the CiviCDR team it is likely that IPs and SPs will be able to use the current workflow. The platform will likely have to be changed in the future to allow for shared tickets so that it can accommodate a more traditional individual user account setup.

**Comment by tiffrobo** [comment]
Closing and creating a question ticket for CDR core link
