### ISSUE TITLE
SP are allowed to change ticket status, but it will not actually change.

### ISSUE THREAD

**Issue by seamustuohy** [ASL-19/civicdr#15]
SP's only have their name, contact, and the ticket status as options in the edit ticket section. But, their modifications to the ticket status are not saved in the interface. If they are supposed to be able to change ticket status the changes should stay, if they are not supposed to be able to change the status they should not have the option in the interface.

After a ticket is assigned to a service provider, the provider is able to change the state of the ticket (eg to resolved etc.). By examining the requests, it can be seen that the server accepts the state change but as soon as the status of the ticket is fetched from the server again, it has still its old value. The only way to change the status of a ticket seems to be via the admin account.

**Comment by majorzazz** [comment]
I believe this is closed by https://github.com/ASL-19/civicdr/commit/87e129e985a4c71cf16be3348af9d1b942fa07ed. Please reopen if not!

**Comment by seamustuohy** [comment]
Confirming that this is address. Thanks!
