### ISSUE TITLE
Admin users cannot delete tickets

### ISSUE THREAD

**Issue by seamustuohy** [ASL-19/civicdr#19]
I currently cannot delete user tickets from an admin account. When I try to the response is `{"error":"Server error!"}` 

This started when I attempted to delete a user who had a ticket open for them. The system would no longer let me delete that user, and it would not let me delete that ticket. Furthermore, it won't let me delete any other tickets.

@MayaAvaz Could you try to delete a ticket from an admin account to confirm that this is not working?

**Comment by MayaAvaz** [comment]
@seamustuohy I cannot delete either.

**Comment by majorzazz** [comment]
This was some foreign-key database corruption in the `reads` table, as supposed by @seamustuohy. I've fixed the staging database, and have the above PR in on the back-end to solve this problem.

**Comment by seamustuohy** [comment]
Per my test this morning (documented in [issue 5 of civicdr-backend](https://github.com/ASL-19/civicdr-backend/issues/5) ) This still looks to be occuring.

**Comment by seamustuohy** [comment]
Fixed in the [latest commit 6682778 ](https://github.com/ASL-19/civicdr-backend/commit/668277836d18a455a53589d9b283f428f97393e2). The code from the last commit was correct, but the 'read' table deletion just needed to be moved up above the 'ticket' table deletion.
