### ISSUE TITLE
CDR-01-001 Web: Complete lack of HTTP Security headers

### ISSUE THREAD

**Issue by seamustuohy** [ASL-19/civicdr#23]
It was found that the frontend and backend websites fail to deploy HTTP Security headers. This unnecessarily exposes CiviCDR users to Clickjacking, XSS, TLS channel downgrade attacks and other similar client-side attacks. The issue can be replicated as one navigates to the website and backend URLs provided next. Note to observe the returned HTTP headers.

It is recommended to change the above header composition to something like the following. Please note that fixing the headers on the amazonaws.com subdomain will require employing a web server other than Amazon S3 since the S3 does not allow custom HTTP headers.

**Comment by seamustuohy** [comment]
We discussed resolving 001 / 002 / 004 with the following options:                                                                                                                                 
                                                                                                                                                                                                   
- Using Cloudfront and Lambda@Edge (ruled out because lambda@edge is alpha)                                                                                                                        
- Using an EC2 or Heroku Nginx service with HTTPs and custom headers config.                                                                                                                       
- Using a static service like Netlify.com <http://netlify.com/>

**Comment by seamustuohy** [comment]
Have your recent updates to the deployment addressed this issue @MayaAvaz ?

**Comment by MayaAvaz** [comment]
@seamustuohy It's fixed in FrontEnd which now returns the proper headers.

**Comment by MayaAvaz** [comment]
Backend is left.

**Comment by seamustuohy** [comment]
I have that one in a [separate issue](https://github.com/ASL-19/civicdr-backend/issues/8). But, that one should also be fixed by close of business. I'm just testing the [fix right now. ](https://github.com/ASL-19/civicdr-backend/pull/25)
