### ISSUE TITLE
CDR-01-002 Web: Lack of TLS on main page enables MitM attacks

### ISSUE THREAD

**Issue by seamustuohy** [ASL-19/civicdr#24]
It was found that the main CiviCDR page is served over clear-text HTTP. While the actual login HTTP requests are performed over TLS to the backend server, an attacker could change the frontend website to ensure that user-credentials are leaked over clear- text HTTP. Given this premise, an attacker would be able to take over user-accounts. 

It is recommended to implement a permanent redirect from clear-text HTTP to HTTPS and to deploy adequate HTTP security headers as proposed under [CDR-01-001.](https://github.com/ASL-19/civicdr/issues/23) This would help mitigate the channel downgrade attacks.

**Comment by seamustuohy** [comment]
We discussed resolving 001 / 002 / 004 with the following options:                                                                                                                                 
                                                                                                                                                                                                   
- Using Cloudfront and Lambda@Edge (ruled out because lambda@edge is alpha)                                                                                                                        
- Using an EC2 or Heroku Nginx service with HTTPs and custom headers config.                                                                                                                       
- Using a static service like Netlify.com <http://netlify.com/>

**Comment by seamustuohy** [comment]
Have your recent updates to the deployment addressed this issue @MayaAvaz ? It seems so.

**Comment by MayaAvaz** [comment]
@seamustuohy The website is now served from the proper URL with a certificate.
