### ISSUE TITLE
CDR-01-004 Web: Amazon S3 Bucket name vulnerable to Cookie Bomb

### ISSUE THREAD

**Issue by seamustuohy** [ASL-19/civicdr#25]
It was found that the frontend website hosted on Amazon S3 uses a bucket name that could be vulnerable to a Cookie Bomb attack. An attacker can set up a malicious website that is also hosted on the same region and cause a Denial of Service for the users who visit it.

Since anyone can set up their own bucket under the shared s3-website-COUNTRY-REGION-1.amazonaws.com domain, an attacker can prepare a website that sets a significant amount of cookies on the shared domain. This can affect other websites on the same domain, including CiviCDR. As a result, the server will reject every incoming request as it contains a large header.

It is recommended to change the bucket name. The new name should not contain the dot character, so that a transition would mean moving from civicdr.org to civicdr-org, for example. This way no other websites can influence the cookies on the domains as they are protected by the Public Suffix List 2 . Ideally, it should be considered to move the website away from Amazon S3 in order to globally resolve the issues noted in [CDR-01-001](https://github.com/ASL-19/civicdr/issues/23) and [CDR-01-002](https://github.com/ASL-19/civicdr/issues/24) as well.

**Comment by seamustuohy** [comment]
We discussed resolving 001 / 002 / 004 with the following options:                                                                                                                                 
                                                                                                                                                                                                   
- Using Cloudfront and Lambda@Edge (ruled out because lambda@edge is alpha)                                                                                                                        
- Using an EC2 or Heroku Nginx service with HTTPs and custom headers config.                                                                                                                       
- Using a static service like Netlify.com <http://netlify.com/>

**Comment by seamustuohy** [comment]
Have your recent updates to the deployment addressed this issue @MayaAvaz ?

**Comment by MayaAvaz** [comment]
@seamustuohy The site is now served on proper name. S3 will be disabled soon.
