### ISSUE TITLE
Improve “Filter Tickets” component overflow styling

### ISSUE THREAD

**Issue by GrantASL19** [ASL-19/civicdr#30]
The current styling of the “Filter Tickets” component is odd:

![filter-tickets-current](https://user-images.githubusercontent.com/30265160/28339399-14383360-6bda-11e7-96c2-15ebd57b00db.png)

Why not remove the internal scrolling and show the full list of selections? This would really improve the UX on mobile, where scroll gutters are hidden (so the overflow might not even be perceptible) and internal scrolling can be a really awkward interaction.

![filter-tickets-no-scroll](https://user-images.githubusercontent.com/30265160/28339483-3f3bbbb8-6bda-11e7-841d-035c7705cbf8.png)

If you want to keep the scrolling, it would look better if you set `overflow-y: scroll` rather than `overflow: scroll` (and added some padding-right):

![filter-tickets-overflow-y](https://user-images.githubusercontent.com/30265160/28339653-cff58c92-6bda-11e7-98ff-b902a7f0c6c8.png)

**Comment by tiffrobo** [comment]
Closing ticket and created similar suggestion on DSX
