### ISSUE TITLE
Service providers can’t change their passwords via the web interface

### ISSUE THREAD

**Issue by GrantASL19** [ASL-19/civicdr#32]
It appears that the only way for a service provider (and presumably an implementing partner) to change their password is to trigger a password reset via the Auth0 interface. This seems like something that should be possible directly within the interface.

**Comment by seamustuohy** [comment]
During the development phase we decided to offload all authorization functions to Auth0 so that we would be able to transfer much of that risk to their service. Including authorization account management functions within the platform would mean increasing our attack surface somewhat substantially.

**Comment by tiffrobo** [comment]
Created ticket on DSX
