### ISSUE TITLE
Site silently fails to load on many browsers

### ISSUE THREAD

**Issue by GrantASL19** [ASL-19/civicdr#37]
The browser compatibility is pretty limited at the moment. Based on some quick testing, the site only seems to work on the latest versions of Chrome (and Chromium-based browsers), Firefox, Safari, and Edge.

Notably, it doesn’t load on the following browsers:

- All versions of Internet Explorer, including 11.

- All versions of Android WebKit. This was the default browser and web view engine on Android until 5.0, and the basis for some skinned manufacturer-bundled browsers. Even if these users install and use Chrome, Android WebKit is (to my knowledge) still used to render web views in other apps, including social media apps that people could be referred to CiviCDR from. In our experience the 4.4 browser (roughly equivalent to Chromium 30) and to a much lesser degree the 4.1 browser (roughly equivalent to Chromium 12!) are still out there.

- All versions of Samsung Internet until 5.0, which only started getting bundled with Samsung phones this year. There are a ton of popular Samsung devices out there that shipped with earlier versions, and a lot of them can’t update to 5.0. Samsung Internet is essentially just a wrapper around Chromium – you can see a rough breakdown of the equivalent versions [here](https://gist.github.com/NielsLeenheer/4daa6a9ce7f4a0f4733d).

- Opera Mini in proxy (“Extreme”) mode. This browser isn’t popular in the west, but it’s overwhelmingly popular in a lot of the developing world. Probably pretty difficult to support since it has pretty severe JS restrictions due to the proxy architecture, but would be nice to have all things being equal.

When I say the site doesn’t load, I mean that there’s a blank white screen with no explanation (I’ve attached a few screenshots). This means that a non-trivial percentage of potential IPs (who I think it’s safe to say won’t necessarily be using the latest devices or browsers) are going to hit a brick wall.

The immediate cause of all of these failures seems to be that the affected browsers don’t support [ES6 Object.assign](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign), but I’m guessing there are other incompatibilities if you’re using ES6 features.

I’m not familiar enough with React to get into the code and evaluate how difficult expanding the browser compatibility would be, but I assume it wouldn’t be easy to cover a lot of these browsers without fundamentally rewriting a lot of stuff and possibly changing the underlying framework. I’m also not sure if evergreen-only browser compatibility was formally decided.

At the very least, there should be a default message (baked into the SPA base index page) informing users that their browser isn’t supported if the site fails to bootstrap/load, and prompting them to send us an email if they don’t know how to proceed.

IE11 on Windows 10:

![login-page-ie11-win10](https://user-images.githubusercontent.com/30265160/28438876-a721e556-6d6d-11e7-90df-72a094cd9aa5.jpg)

Android WebKit on stock Android 4.4:

![login-page-android-webkit-4 4](https://user-images.githubusercontent.com/30265160/28438906-c4308e68-6d6d-11e7-8753-3c9b61df3743.png)

Samsung Internet on a Galaxy S7:

![login-page-samsung-internet-4 0-galaxy-s7](https://user-images.githubusercontent.com/30265160/28438930-d9deea66-6d6d-11e7-967e-6d7a46ad9cef.png)

**Comment by seamustuohy** [comment]
We can try to use [babel pollyfill](https://babeljs.io/docs/usage/polyfill/) to emulate the full ES2015+ environments that are unsupported on these less modern browser stacks. We could try to just replace [object.assign](https://babeljs.io/docs/plugins/transform-object-assign/) but, i suspect we will hit additional ES2016 features beyond it.

## References
- https://stackoverflow.com/questions/36264993/how-can-i-use-babel-polyfill-to-support-all-ie11-issues-with-gulp

**Comment by GrantASL19** [comment]
If you can polyfill to a point where it works in older browsers that would be better than nothing, but it’s also not ideal to bundle in a bunch of polyfills that will increase the size of the site code and perform worse than native methods. I realize it’s too late to fix the underlying causes since the decision to build on ES6/2015 is baked into the site at this point, but please do what you can.

If nothing else, there should be a browser compatibility notice if the site fails to load – a white screen is untenable.

**Comment by GrantASL19** [comment]
(Closed by mistake – reopening!)

**Comment by seamustuohy** [comment]
A browser compatibility notice is more than possible before launch. We can likely add the other features later. (

**Comment by seamustuohy** [comment]
A compatibility notice has been added. I am also taking the following action:
- I'm leaving this issue open.
- I'm removing it from the launch milestone to reflect that the milestone level fix is implemented.
- I'm adding the label "enhancement" to reflect that we would like to implement a full fix in the future.

**Comment by tiffrobo** [comment]
>A compatibility notice has been added. I am also taking the following action:
I'm adding the label "enhancement" to reflect that we would like to implement a full fix in the future.

@levjoy Can you have a look at this and see if we still need the ticket for DSX? Or assign it to someone who can. We tested on our browers, and if they are not compatable you get a message asking you to use a different browser. We can create a ticket for the full fix enhancement shown above....
