### ISSUE TITLE
Handle connection refused from API

### ISSUE THREAD

**Issue by seamustuohy** [ASL-19/civicdr#4]
If the API doesn't respond after login, the whole app doesn't load. We should flash an error somewhere 

This is still relevant, after switching from our login modal to Auth0's. This happens if for example the API is down, nothing gets loaded. 

We should pop up a modal that prevents login if the API is down

Something like the following

### Create this new file

```app/assets/scripts/components/api-status-modal.js```

```js
'use strict';
import React from 'react';

var StatusModal = React.createClass({
  render: function () {
    return (
      <section className='modal modal--medium delete-modal'>
        <div className='modal__inner'>
          <div className='warning__group'>
            <h2 className='inpage__title heading--small'>The API is currently unavailable.</h2>
            <p className='inpage__description'>Please check back later.</p>
          </div>
        </div>
      </section>
    );
  }
});
module.exports = StatusModal;
```

### Add the following lines to this file.

```app/assets/scripts/views/tickets.js```

Add in the top
```js
import StatusModal from '../components/api-status-modal';
```

add this StatusModal line in the following section (indicated with a plus);

```js
    const ticketsToDisplay = tickets.filter(this.filterTicket.bind(this));
    const checked = tickets.filter(t => t.checked);
    return (
      <section className="section">
+      <StatusModal/>
        <div className="dashboard">
          <header className="inpage__header">
            <div className="inner">
              <div className="inpage__headline">
```

**Comment by tiffrobo** [comment]
Is this relevant to our DSX site or mobile version? @n8fr8 @levjoy
