### ISSUE TITLE
Server-dependent actions silently fail if associated requests fail

### ISSUE THREAD

**Issue by GrantASL19** [ASL-19/civicdr#43]
(This is sort of a meta-issue, since AFAIK it probably encompasses changing the logic of several controllers.)

If the user performs an action and the associated request fails, the site should display an explanatory error message.

In the context of an SP, these actions include:

- Submitting a comment
- Deleting a comment
- Submitting the “Edit Provider” overlay form (this one is more significant because the overlay disappears as it would if the request succeeded; if the user doesn’t notice that the underlying screen hasn’t changed, they won’t realize that the submissions failed, and will probably navigate away and lose their changes)

This could happen if their token has expired, their network connection has dropped, or the server fails to respond for some reason.

## Steps to reproduce

- Open a ticket page
- Delete the id_token localStorage entry
- Attempt to submit a comment

## Actual result

Nothing happens. The error console contains the following:

```
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (messages, line 0)
[Error] Unhandled Promise Rejection: Error: Request failed with status code 401
```

## Expected result

Error message should appear, and if applicable any associated state change or navigation should be cancelled. This could be an in-page error message, or even a simple `alert()`.

**Comment by seamustuohy** [comment]
Addressed by PR #54
