### ISSUE TITLE
Admin view: text in ticket's Notes and IP/SP thread sections

### ISSUE THREAD

**Issue by MayaAvaz** [ASL-19/civicdr#60]
Logged in as admin to the platform. 
Opened a ticket. Started typing under Notes section. The text shows up under IP Thread and SP Thread. The same behaviour for text being typed in IP Thread or SP Thread.
This is very error prone and pose a risk of mistakenly sending a comment to wrong target, for example sending an internal note to IP or SP.

**Comment by tiffrobo** [comment]
This is fixed. Closing.
