### ISSUE TITLE
Typo in 'Create Partner Profile' page

### ISSUE THREAD

**Issue by MayaAvaz** [ASL-19/civicdr#62]
On 'Create Partner Profile' page, we have:
Notification Preferences
Which informational notifications would you like to receive from CiviCDR? (These do not include platform notifications which can be turned off **_below_**.)

The platform notification setting is located **_above_** this section, not **_below_**.

**Comment by tiffrobo** [comment]
@MayaAvaz Is this typo in the Admin view? Do you know if there is still a typo?

**Comment by MayaAvaz** [comment]
@tiffrobo It is in Partner view. When they first log into the platform they have to create a profile. The typo still exist on 'Create Partner Profile' page.

**Comment by tiffrobo** [comment]
@MayaAvaz Thank you

**Comment by tiffrobo** [comment]
Closing this ticket and adding the update to the DSX IP profile enhancements ticket
