### ISSUE TITLE
Copy-editing & spell checking needed on service-type descriptions. 

### ISSUE THREAD

**Issue by seamustuohy** [ASL-19/civicdr#63]
For instance [misspellings of constituents as constitutants.](https://github.com/ASL-19/civicdr/blob/master/app/assets/scripts/constants.js#L37)

**Comment by tiffrobo** [comment]
@seamustuohy Has spell check been implemented? Or do we need a copy editor to review?

**Comment by seamustuohy** [comment]
You would have to check with the team from ASL-19 they maintained the code after my bootstrapping contract ended.

**Comment by tiffrobo** [comment]
I will spell check and edit then upload to DSX with correct language and layout
