### ISSUE TITLE
Ticket titles don't show properly

### ISSUE THREAD

**Issue by MayaAvaz** [ASL-19/civicdr#65]
Logged in as admin. Clicked on one of the partners. Showing Tickets for partners: The tickets for that partner showed but the titles are partner's name as oppose to ticket titles. 
The creation date for those tickets also shown as today instead of the actual creation date. 
![screen shot 2017-09-19 at 13 15 34](https://user-images.githubusercontent.com/28363288/30605593-a8b4d528-9d3c-11e7-8c52-6c50471f5295.png)

**Comment by tiffrobo** [comment]
Closing this ticket and creating a new ticket on DSX ops site.
