### ISSUE TITLE
When adding SPs, an entirely blank search field does not show all SPs

### ISSUE THREAD

**Issue by seamustuohy** [ASL-19/civicdr#9]
## How to duplicate:
An admin clicks "assign to service provider" button on a ticket. Admin does not modify any of filtering fields. Admin clicks on service provider drop down.

## What I thought should happen:
A list of all SPs in the system is shown

## What did happen
Only a subset of SPs was shown.

**Comment by majorzazz** [comment]
Hmm, I cannot replicate this myself locally. Can you provide more replication details, or a screencast GIF or the like?

**Comment by tiffrobo** [comment]
Not seeing this anymore, so I will close it.
